# HW3: Fundamental indicators

Project 1 grouped stocks around the shipping disruption thesis. This notebook keeps those groups and looks at valuation, profitability, and debt over time.

Each ticker gets four charts with time on the x-axis. Each indicator is overlaid with the stock price: the colored solid line uses the left axis, and the gray dashed price line uses the right axis.

Run this notebook in the **QuantConnect Research environment**, from top to bottom. The dates below can be changed!

## Indicators

| Indicator | Meaning | What to look for |
| --- | --- | --- |
| P/E | Share price divided by earnings per share | Lower can mean cheaper, but a cyclical company can look cheap when earnings are temporarily high. Missing or nonpositive P/E is left blank. |
| Free cash flow yield | Free cash flow per share divided by share price | Higher means more cash generation relative to price. Negative values are kept: the company is consuming cash. |
| Operating margin | Operating income divided by revenue | Shows how much revenue remains after operating expenses. A rising margin may suggest better pricing or cost control. |
| Debt/assets | Interest-bearing debt divided by total assets | Shows how much of the asset base is financed with debt. Lower usually means less leverage, although normal levels differ by industry. |

Operating margin and debt/assets use Morningstar's **OneYear** fields (the period dictionary calls this `1Y`). Debt/assets is a balance-sheet ratio, not a sum of debt over a year. Percentage charts convert decimal ratios to percent.

Accounting measures usually change around reports, so flat stretches are expected. P/E and cash flow yield can also change as the share price moves. Separate panels keep the units readable; the vertical scales differ across tickers. Compare firms within a group first.

**Stock price comparison:** The dashed line is the daily closing price in US dollars, adjusted for splits but not dividends. It is a price series, not total investment return. The two y-axes use different scales: line crossings have no particular meaning. P/E and cash flow yield already include price in their formulas, so some co-movement is mechanical rather than evidence of predictive power.

In [ ]:
from AlgorithmImports import *
from QuantConnect.Research import QuantBook
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from IPython.display import display

qb = QuantBook()
START = datetime(2018, 1, 1)
END = datetime(2026, 10, 17)  # exclusive; use completed historical dates

GROUPS = {
    "Aluminum": ["AA", "CENX", "RIO"],
    "LNG / Natural Gas": ["LNG", "EQT", "AR", "GLNG"],
    "Fertilizer": ["CF", "MOS", "IPI"],
    "Defense": ["LMT", "RTX", "NOC"],
    "Tankers": ["FRO", "STNG", "INSW"],
    "Container Shipping": ["GSL"],
}

# Cache numeric data so rerunning a chart doesn't request history again.
cache = {}
plt.rcParams.update({"figure.dpi": 110, "axes.spines.top": False,
                     "axes.spines.right": False, "font.size": 10})

## Load and plot

The helper below requests each ticker's daily fundamental history and stores the four numeric series plus daily stock prices. Missing values stay missing; nothing is backfilled from later reports. Dates show when observations appear in the dataset, not the fiscal period being described.

The coverage table reports the share of returned observations with usable values. It does not measure how often a company published new accounts. An empty panel means there is no usable data for that indicator in the requested window. A failed history request is printed so it can be checked rather than mistaken for missing data.

In [27]:
COLUMNS = ["P/E", "FCF yield (%)", "Operating margin (%)", "Debt/assets (%)"]


def number(value):
    if value is None:
        return np.nan
    value = float(value)
    return value if np.isfinite(value) else np.nan


def annual_value(field):
    # Use the same period across companies; don't silently switch periods.
    # Dictionary keys are abbreviated: "1Y", not the property name "OneYear".
    periods = field.get_period_values()
    return number(periods["1Y"]) if "1Y" in periods else np.nan


# Discard data extracted with an earlier version of the helper.
cache.clear()


def load_ticker(ticker):
    key = (ticker, START, END)
    if key in cache:
        return cache[key]
    symbol = qb.add_equity(ticker, Resolution.DAILY).symbol
    rows = []
    for f in qb.history[Fundamental](symbol, START, END):
        if not f.has_fundamental_data:
            continue
        pe = number(f.valuation_ratios.pe_ratio)
        rows.append({
            "date": f.end_time,
            "P/E": pe if pe > 0 else np.nan,
            "FCF yield (%)": 100 * number(f.valuation_ratios.fcf_yield),
            "Operating margin (%)": 100 * annual_value(f.operation_ratios.operation_margin),
            "Debt/assets (%)": 100 * annual_value(f.operation_ratios.debt_to_assets),
        })
    if rows:
        df = pd.DataFrame(rows).set_index("date").sort_index()
        df = df.loc[~df.index.duplicated(keep="last")]
    else:
        df = pd.DataFrame(columns=COLUMNS, index=pd.DatetimeIndex([], name="date"))
    # Keep the price dates separate: no artificial alignment or forward filling.
    prices = qb.history(
        symbol, START, END, Resolution.DAILY,
        data_normalization_mode=DataNormalizationMode.SPLIT_ADJUSTED,
        fill_forward=False,
    )
    if not prices.empty:
        close = prices["close"]
        if isinstance(close.index, pd.MultiIndex):
            close = close.xs(symbol, level=0)
        close = close.sort_index().astype(float)
        df.attrs["price"] = close
    else:
        df.attrs["price"] = pd.Series(dtype=float)
        print(f"{ticker}: no price history returned.")
    cache[key] = df
    return df


def plot_ticker(ticker, df):
    fig, axes = plt.subplots(2, 2, figsize=(13, 6.5), sharex=True)
    for ax, column, color in zip(axes.flat, COLUMNS,
                                  ["#376795", "#29866d", "#a97229", "#8a649b"]):
        series = df[column]
        if series.notna().any():
            # Keep gaps visible. No interpolation, clipping, or smoothing.
            ax.plot(df.index, series, color=color, linewidth=1.4, label=column)
            if column != "P/E":
                ax.axhline(0, color="gray", linewidth=0.6, alpha=0.6)
        else:
            ax.text(0.5, 0.5, "No usable data", ha="center", va="center",
                    transform=ax.transAxes, color="gray")
        price_ax = ax.twinx()
        price = df.attrs.get("price", pd.Series(dtype=float))
        if price.notna().any():
            price_ax.plot(price.index, price, color="#555555", linestyle="--",
                          linewidth=1.0, alpha=0.7, label="Stock price")
        else:
            price_ax.text(0.98, 0.05, "No price data", ha="right",
                          transform=price_ax.transAxes, color="gray", fontsize=8)
        price_ax.spines["right"].set_visible(True)
        price_ax.set_ylabel("Split-adjusted close ($)", color="#555555", fontsize=9)
        price_ax.tick_params(axis="y", labelcolor="#555555", labelsize=8)
        handles, labels = ax.get_legend_handles_labels()
        price_handles, price_labels = price_ax.get_legend_handles_labels()
        if handles or price_handles:
            ax.legend(handles + price_handles, labels + price_labels,
                      loc="upper left", fontsize=8, framealpha=0.75)
        ax.set_title(column, loc="left", fontsize=10)
        ax.set_ylabel("times" if column == "P/E" else "%", color=color)
        ax.tick_params(axis="y", labelcolor=color)
        ax.set_xlim(START, END)
        locator = mdates.AutoDateLocator(minticks=3, maxticks=6)
        ax.xaxis.set_major_locator(locator)
        ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(locator))
        ax.grid(alpha=0.2)
    for ax in axes[-1]:
        ax.set_xlabel("Time")
    fig.suptitle(ticker, fontsize=14, fontweight="bold")
    fig.tight_layout()
    plt.show()
    plt.close(fig)


def explore_group(group):
    coverage = []
    for ticker in GROUPS[group]:
        try:
            df = load_ticker(ticker)
        except Exception as error:
            print(f"{ticker}: history failed — {type(error).__name__}: {error}")
            continue
        plot_ticker(ticker, df)
        coverage.append({
            "Ticker": ticker,
            "First observation": str(df.index.min().date()) if len(df) else "none",
            "Last observation": str(df.index.max().date()) if len(df) else "none",
            "Observations": len(df),
            **{c: round(100 * df[c].notna().mean(), 1) if len(df) else 0
               for c in COLUMNS},
        })
    print("Coverage: indicator columns below show % of observations with usable data.")
    display(pd.DataFrame(coverage))

## Correlation checks

Each industry section also reports **Pearson correlation** for each ticker and indicator, using one observation per completed calendar month.

- **With price:** compares the indicator with the stock price at the same observation. This describes co-movement in the charts.
- **With next-month return:** compares the indicator with the price return to the next monthly observation. This is a first check for a possible trading signal.
- **N:** number of usable monthly pairs behind each result. Fewer than 12 pairs or a constant series produces a blank correlation.

Values run from -1 to +1. Positive means the two variables tend to move in the same direction; negative means they tend to move in opposite directions. A value near zero means little linear relationship.

For each month, use the last available daily close and only fundamental observations timestamped at or before that close's timestamp. Partial months are excluded. Missing indicators are not filled from future observations. Monthly sampling reduces repeated daily accounting observations, though months still share reported accounts.

Price-level correlation can reflect shared trends. P/E and cash flow yield also contain price in their formulas. The following-month return column is more relevant to strategy research, but it is descriptive evidence, not proof of predictability. These are split-adjusted **price returns**, excluding dividends, trading costs, and execution effects. No significance claim is made.

In [28]:
def monthly_pairs(df):
    price = df.attrs.get("price", pd.Series(dtype=float)).dropna()
    if price.empty or df.empty:
        return pd.DataFrame(columns=COLUMNS + ["Price", "Next-month return"])

    def clean_index(frame):
        frame = frame.copy()
        frame.index = pd.to_datetime(frame.index)
        if frame.index.tz is not None:
            frame.index = frame.index.tz_localize(None)
        return frame.sort_index().loc[lambda x: ~x.index.duplicated(keep="last")]

    prices = clean_index(price.to_frame("Price"))
    fundamentals = clean_index(df[COLUMNS])
    # Keep the actual timestamp of the last close in each completed month.
    periods = prices.index.to_period("M")
    prices = prices.loc[periods.end_time < pd.Timestamp(END)]
    monthly = prices.groupby(prices.index.to_period("M"), sort=True).tail(1)
    if monthly.empty:
        return pd.DataFrame(columns=COLUMNS + ["Price", "Next-month return"])
    aligned = pd.merge_asof(
        monthly.rename_axis("date").reset_index(),
        fundamentals.rename_axis("date").reset_index(),
        on="date", direction="backward",
    ).set_index("date")
    next_return = aligned["Price"].shift(-1) / aligned["Price"] - 1
    # A gap in price coverage must not turn a multi-month return into one month.
    months = pd.Series(aligned.index.to_period("M").asi8, index=aligned.index)
    aligned["Next-month return"] = next_return.where(months.shift(-1) - months == 1)
    return aligned


def correlation_table(group):
    rows = []
    for ticker in GROUPS[group]:
        df = cache.get((ticker, START, END))
        if df is None:
            continue  # A failed history request was reported above.
        monthly = monthly_pairs(df)
        for indicator in COLUMNS:
            row = {"Ticker": ticker, "Indicator": indicator}
            for target, label in [("Price", "With price"),
                                  ("Next-month return", "With next-month return")]:
                pairs = monthly[[indicator, target]].replace([np.inf, -np.inf], np.nan).dropna()
                enough = len(pairs) >= 12 and (pairs.nunique() > 1).all()
                row[label] = pairs[indicator].corr(pairs[target]) if enough else np.nan
                row[label + " N"] = len(pairs)
            rows.append(row)
    if not rows:
        print("No data available for correlation.")
        return
    table = pd.DataFrame(rows).set_index(["Ticker", "Indicator"])
    display(table.style.format({"With price": "{:.2f}",
                                "With next-month return": "{:.2f}"}, na_rep="—"))

## 1. Aluminum

**AA, CENX, RIO**

Do higher margins come with stronger cash generation? Does a low P/E persist, or mainly appear during earnings peaks? RIO is a diversified miner, so it is not a pure aluminum comparison.

In [29]:
explore_group('Aluminum')
correlation_table('Aluminum')

https://s3.amazonaws.com/research.quantconnect.com/images/5af9035a-ef80-4367-b217-f97fe52d33eb.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=8gTk0vGVZtHy8232DfQfAoHjpqQ%3D&Expires=1792865534

https://s3.amazonaws.com/research.quantconnect.com/images/efa21bfa-9def-4b81-81e0-b0dde8a6fa47.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=tWCQpjgHiWPodIb6TmNWr5%2BLlxQ%3D&Expires=1792865538

https://s3.amazonaws.com/research.quantconnect.com/images/f7baa894-c6bc-4b7d-b2f0-7db8a8777df7.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=B55ieNvnE0qEikvKsUA%2B4Ezc0vQ%3D&Expires=1792865543

Coverage: indicator columns below show % of observations with usable data.

,Ticker,First observation,Last observation,Observations,P/E,FCF yield (%),Operating margin (%),Debt/assets (%)
0,AA,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
1,CENX,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
2,RIO,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0

## 2. LNG / Natural Gas

**LNG, EQT, AR, GLNG**

Does cash generation improve alongside margins? Do the more leveraged firms look cheaper? Producers, export terminals, and floating LNG assets have different business models, even though they share the same theme.

In [30]:
explore_group('LNG / Natural Gas')
correlation_table('LNG / Natural Gas')

https://s3.amazonaws.com/research.quantconnect.com/images/dd740afd-8ef5-4fcf-8649-623bcbb3b1a6.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=zbPMa4DPF3tWBn5Mt5jDo7DJDrs%3D&Expires=1792865548

https://s3.amazonaws.com/research.quantconnect.com/images/406d3eb3-545e-45f2-962a-e3029e61cfe0.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=Lz5fwPdGqxn%2ByDInbu9hwWQ8kTY%3D&Expires=1792865553

https://s3.amazonaws.com/research.quantconnect.com/images/1e4cf20e-eb20-413d-9ee9-926251b494c4.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=OBXRSJCkh5MDEcMpRlGkY8WEiQI%3D&Expires=1792865558

https://s3.amazonaws.com/research.quantconnect.com/images/d09df9f8-31d2-4020-a75e-86f54acb8572.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=B1Pg0DWIvjR4RaeqTgGWdkUcN7Q%3D&Expires=1792865563

Coverage: indicator columns below show % of observations with usable data.

,Ticker,First observation,Last observation,Observations,P/E,FCF yield (%),Operating margin (%),Debt/assets (%)
0,LNG,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
1,EQT,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
2,AR,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
3,GLNG,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0

## 3. Fertilizer

**CF, MOS, IPI**

Look for periods when margins and cash flow yield rise together. Are low valuations associated with an earnings peak? Nitrogen, phosphate, and potash producers have different input costs.

In [31]:
explore_group('Fertilizer')
correlation_table('Fertilizer')

https://s3.amazonaws.com/research.quantconnect.com/images/863b274b-2bd3-49c9-af33-1fbb1a17fd4a.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=Wq3Pg5jT9q%2BgeXSxjza%2B%2B6M7pCo%3D&Expires=1792865568

https://s3.amazonaws.com/research.quantconnect.com/images/cd4617bf-0c99-4ecd-bab0-bad218e48bf5.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=q2Q%2FFq2%2BZKJjwDoWZMzwodxYbRc%3D&Expires=1792865573

https://s3.amazonaws.com/research.quantconnect.com/images/2749d389-8b2b-4d3f-ba2f-577ab9c02e50.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=29r8%2BnUNW3c1Z8ciLkD8ojWrlrY%3D&Expires=1792865578

Coverage: indicator columns below show % of observations with usable data.

,Ticker,First observation,Last observation,Observations,P/E,FCF yield (%),Operating margin (%),Debt/assets (%)
0,CF,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
1,MOS,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
2,IPI,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0

## 4. Defense

**LMT, RTX, NOC**

Are margins steadier than in the commodity groups? Does a valuation premium line up with more consistent cash generation? These measures do not directly measure contract backlogs.

In [32]:
explore_group('Defense')
correlation_table('Defense')

https://s3.amazonaws.com/research.quantconnect.com/images/bfba1a12-b2c8-4a35-b986-85c7dca962ef.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=b1WOqdDz0SXACFtI7%2Feuy%2BcctoE%3D&Expires=1792865583

https://s3.amazonaws.com/research.quantconnect.com/images/0ed2b559-36d3-421d-8694-dfe6faa542fd.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=MFuec46vfwQ7WhewF%2BFbcPjs55c%3D&Expires=1792865588

https://s3.amazonaws.com/research.quantconnect.com/images/100eaec6-95f9-4264-a7a1-f92c9cf5fcbd.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=nsXGrBZQiuLKfFysPfNY5OCL3No%3D&Expires=1792865593

Coverage: indicator columns below show % of observations with usable data.

,Ticker,First observation,Last observation,Observations,P/E,FCF yield (%),Operating margin (%),Debt/assets (%)
0,LMT,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
1,RTX,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
2,NOC,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0

## 5. Tankers

**FRO, STNG, INSW**

How sharply do profitability and cash flow change across shipping cycles? Does leverage fall in strong periods? These names also connect to the FRO and multi-stock technical strategies in Project 2.

In [33]:
explore_group('Tankers')
correlation_table('Tankers')

https://s3.amazonaws.com/research.quantconnect.com/images/e8f97f97-d641-41e4-9897-5a63940669a5.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=vTbp%2FhN3ukKY%2F%2F8CR0VOXqPb3ug%3D&Expires=1792865598

https://s3.amazonaws.com/research.quantconnect.com/images/3d6e9819-27a8-43d4-910d-a1f3467b0177.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=pjBar89NxXoo49%2B58wA1KYdDwl4%3D&Expires=1792865603

https://s3.amazonaws.com/research.quantconnect.com/images/a73187a0-5f33-4415-b929-9e3389de1952.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=ubjvkVAIYbG3zF5c9Ykq3lU4PPw%3D&Expires=1792865608

Coverage: indicator columns below show % of observations with usable data.

,Ticker,First observation,Last observation,Observations,P/E,FCF yield (%),Operating margin (%),Debt/assets (%)
0,FRO,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
1,STNG,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0
2,INSW,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0

## 6. Container Shipping

**GSL**

Does cash generation stay relatively steady as valuation changes? GSL leases ships under charters, so its financial results may adjust more slowly than spot freight rates. This group has only one stock; compare its own history rather than claiming a within-group ranking.

In [34]:
explore_group('Container Shipping')
correlation_table('Container Shipping')

https://s3.amazonaws.com/research.quantconnect.com/images/de6b6663-3aa6-495d-94f5-291676abd6b3.png?AWSAccessKeyId=AKIAY3TRDSUSL3ZLVGGZ&Signature=%2BGVmvVCugmZsjyt1EU%2BMBEX2SP0%3D&Expires=1792865613

Coverage: indicator columns below show % of observations with usable data.

,Ticker,First observation,Last observation,Observations,P/E,FCF yield (%),Operating margin (%),Debt/assets (%)
0,GSL,2018-01-03,2026-10-17,2210,100.0,100.0,100.0,100.0

## Indicator summary

These tables summarize each indicator's correlation with the following month's
stock return. Each ticker is measured separately, then the correlations are
averaged overall and within each industry group.

- **Average correlation:** direction of the relationship. Positive means higher
  indicator values tend to precede higher returns; negative means the reverse.
- **Average absolute correlation:** strength within individual stocks, regardless
  of direction. Higher values may hide opposite relationships across stocks.
- **Positive share:** percentage of tickers with positive correlations. Values
  near 50% suggest the direction varies across companies.
- **Tickers / Monthly pairs:** amount of data behind the summary.

Each ticker receives equal weight. At least 12 usable monthly pairs are required.

In [35]:
# Correlation of each indicator with the following month's price return.
MIN_PAIRS = 12
results = []

for sector, tickers in GROUPS.items():
    for ticker in tickers:
        df = cache.get((ticker, START, END))
        if df is None:
            continue

        monthly = monthly_pairs(df)

        for indicator in COLUMNS:
            pairs = (
                monthly[[indicator, "Next-month return"]]
                .replace([np.inf, -np.inf], np.nan)
                .dropna()
            )

            if len(pairs) < MIN_PAIRS or (pairs.nunique() < 2).any():
                continue

            correlation = pairs[indicator].corr(
                pairs["Next-month return"]
            )

            if np.isfinite(correlation):
                results.append({
                    "Sector": sector,
                    "Ticker": ticker,
                    "Indicator": indicator,
                    "Correlation": correlation,
                    "Monthly pairs": len(pairs),
                })

indicator_results = pd.DataFrame(results)


def summarize_indicators(data, group_columns):
    return (
        data.groupby(group_columns)
        .agg(
            Tickers=("Ticker", "nunique"),
            Monthly_pairs=("Monthly pairs", "sum"),
            Average_correlation=("Correlation", "mean"),
            Average_absolute_correlation=(
                "Correlation", lambda x: x.abs().mean()
            ),
            Positive_share=(
                "Correlation", lambda x: 100 * (x > 0).mean()
            ),
        )
        .rename(columns={
            "Monthly_pairs": "Monthly pairs",
            "Average_correlation": "Average correlation",
            "Average_absolute_correlation": "Average absolute correlation",
            "Positive_share": "Positive share (%)",
        })
    )


def show_summary(table):
    display(
        table.style
        .format({
            "Average correlation": "{:+.3f}",
            "Average absolute correlation": "{:.3f}",
            "Positive share (%)": "{:.0f}%",
        })
        .background_gradient(
            subset=["Average correlation"],
            cmap="RdBu", vmin=-1, vmax=1,
        )
    )


if indicator_results.empty:
    print("No usable results. Run the industry sections first.")
else:
    print("OVERALL — equal weight per ticker")
    overall_summary = summarize_indicators(
        indicator_results, ["Indicator"]
    ).sort_values("Average absolute correlation", ascending=False)
    show_summary(overall_summary)

    print("\nBY INDUSTRY — equal weight per ticker within each group")
    sector_summary = summarize_indicators(
        indicator_results, ["Sector", "Indicator"]
    )
    show_summary(sector_summary)

    print("\nINDUSTRY COMPARISON — average signed correlation")
    sector_comparison = (
        sector_summary["Average correlation"]
        .unstack("Indicator")
        .reindex(index=list(GROUPS), columns=COLUMNS)
    )
    display(
        sector_comparison.style
        .format("{:+.3f}", na_rep="—")
        .background_gradient(cmap="RdBu", vmin=-1, vmax=1, axis=None)
    )

    print(
        "\nMonthly pairs are summed ticker-month observations, not "
        "independent samples. GSL alone represents Container Shipping."
    )

OVERALL — equal weight per ticker

BY INDUSTRY — equal weight per ticker within each group

INDUSTRY COMPARISON — average signed correlation

Monthly pairs are summed ticker-month observations, not independent samples. GSL alone represents Container Shipping.